In [4]:
import pandas as pd

In [15]:
df=pd.read_csv('customers-100.csv')

## fetch first five row
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,8/24/2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,4/23/2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,NaN,NaN,3/25/2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,6/2/2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",NaN,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,4/17/2021,https://goodwin-ingram.com/

In [16]:
## for the last ten rows
df.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,1/30/2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,7/10/2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,9/18/2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,8/11/2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,3/11/2020,http://www.hatfield-saunders.net/

In [7]:
df.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object

In [17]:
## handling missing vlaue
df.isnull()  ## to find if there is not anyvlaue did not write so there will be true

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
## missing value with diffrent
df.isnull().any(axis=1)

0     False
1     False
2      True
3     False
4      True
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [19]:
df.isnull().sum() ## everywhere is o because there is no missing value in my file

Index                0
Customer Id          0
First Name           0
Last Name            2
Company              0
City                 2
Country              0
Phone 1              1
Phone 2              4
Email                3
Subscription Date    0
Website              2
dtype: int64

In [ ]:
## if there is any missing value we use a fillna and it fill the missing value with 00 there or there is another way to do
##df.fillna(0)
df['phone2_fillNA'] = df['Phone 2'].fillna(df['Phone 2'].mean()) ## it is not working becasue i don't have any thing which is gonna used as integers
df

TypeError: can only concatenate str (not "int") to str

In [26]:
## renaming columns
df=df.rename(columns={'Company Names':'Company Name'})
df.head()

,Index,Customer Id,First Name,Last Name,Company Name,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,8/24/2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,4/23/2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,NaN,NaN,3/25/2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,6/2/2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",NaN,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,4/17/2021,https://goodwin-ingram.com/

In [27]:
## change datatypes
df['Index_new'] = df['Index'].astype(float)
df.head()

,Index,Customer Id,First Name,Last Name,Company Name,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Index_new
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,8/24/2020,http://www.stephenson.com/,1.0
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,4/23/2021,http://www.hobbs.com/,2.0
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,NaN,NaN,3/25/2020,http://www.lawrence.com/,3.0
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,6/2/2020,http://www.good-lyons.com/,4.0
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",NaN,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,4/17/2021,https://goodwin-ingram.com/,5.0

In [29]:
## fill new value with apply a function
df['New Index']=df['Index'].apply(lambda x:x*3)
df.head()

,Index,Customer Id,First Name,Last Name,Company Name,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Index_new,New Index
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,8/24/2020,http://www.stephenson.com/,1.0,3
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,4/23/2021,http://www.hobbs.com/,2.0,6
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,NaN,NaN,3/25/2020,http://www.lawrence.com/,3.0,9
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,6/2/2020,http://www.good-lyons.com/,4.0,12
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",NaN,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,4/17/2021,https://goodwin-ingram.com/,5.0,15

In [ ]:
## Data aggregatting and grouping