In [2]:
import pandas as pd

In [3]:
## series- it is a one-dimentional array like object that can hold any data type. it is similar to column in a table

import pandas as pd
data=[1,2,3,4]
series=pd.Series(data)
print("series \n", series)

series
 0    1
1    2
2    3
3    4
dtype: int64

In [10]:
## creat a series from dictionary
data={'a':1,'b':2, 'c':3}
seires_dict=pd.Series(data)
print(seires_dict)
print(type(seires_dict))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>

In [9]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [27]:
## Data frame
## creat a Dataframe from a dictionary of list

data={
  'Name':['Mohit', 'Rohit', 'Mayank'],
  'Age':[26,20,26],
  'city':['dub', 'gur', 'rai']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age city
0   Mohit   26  dub
1   Rohit   20  gur
2  Mayank   26  rai
<class 'pandas.core.frame.DataFrame'>

In [14]:
## creat a data frame form a list of dictionary
data=[
  {'Name': 'Mohit', 'Age': 26, 'City':'dublin'},
  {'Name': 'Rohit', 'Age': 20, 'City':'dublin'},
  {'Name': 'Mayank', 'Age': 26, 'City':'dublin'},
  {'Name': 'Neha', 'Age': 23, 'City':'dublin'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age    City
0   Mohit   26  dublin
1   Rohit   20  dublin
2  Mayank   26  dublin
3    Neha   23  dublin
<class 'pandas.core.frame.DataFrame'>

In [19]:
df=pd.read_csv('customers-100.csv')
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,8/24/2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,4/23/2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,3/25/2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,6/2/2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,4/17/2021,https://goodwin-ingram.com/

In [20]:
df.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,1/30/2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,7/10/2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,9/18/2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,8/11/2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,3/11/2020,http://www.hatfield-saunders.net/

In [66]:
## accescing data from dataframe
data

{'Name': ['Mohit', 'Rohit', 'Mayank'],
 'Age': [26, 20, 26],
 'city': ['dub', 'gur', 'rai']}

In [67]:
df

    Name  Age city
1  Rohit   21  gur

In [30]:
df['Name']

0     Mohit
1     Rohit
2    Mayank
Name: Name, dtype: object

In [33]:
df.loc[1]

Name    Rohit
Age        20
city      gur
Name: 1, dtype: object

In [32]:
df.iloc[1]

Name    Rohit
Age        20
city      gur
Name: 1, dtype: object

In [ ]:
## accescing the specified element
df.at[2,'Name'] ## here we need to defined indexa and column

'Mayank'

In [39]:
df.at[2, 'Age']

np.int64(26)

In [42]:
## accesing specified element from iat(using indexing)
df.iat[1,0]

'Rohit'

In [43]:
## data manipulation with dataframe
df

     Name  Age city
0   Mohit   26  dub
1   Rohit   20  gur
2  Mayank   26  rai

In [64]:
## adding a column
df['salary']=[50000,60000,55000]
df

ValueError: Length of values (3) does not match length of index (1)

In [49]:
## remove a column (this is not permanant) when we use inplace then we remove it permanantely
df.drop('salary',axis=1,inplace=True)  ## why we are using axis because we want to delete salary column so we need give a vlaue to the top one row we mane it axis=1

In [50]:
df

     Name  Age city
0   Mohit   26  dub
1   Rohit   20  gur
2  Mayank   26  rai

In [51]:
## add something in the column
df['Age']=df['Age']+1
df

     Name  Age city
0   Mohit   27  dub
1   Rohit   21  gur
2  Mayank   27  rai

In [62]:
## to delete a row but for permanant we use the inplace
df.drop(2,inplace=True)

KeyError: '[2] not found in axis'

In [63]:
df

    Name  Age city
1  Rohit   21  gur

    Name  Age city
1  Rohit   21  gur

    Name  Age city
1  Rohit   21  gur

In [71]:
df=pd.read_csv('customers-100.csv')
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,8/24/2020,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,4/23/2021,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,-1199,(496)978-3969x58947,beckycarr@hogan.com,3/25/2020,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,-9892,stanleyblackwell@benson.org,6/2/2020,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,4/17/2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,1/30/2022,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,7/10/2021,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,9/18/2021,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,8/11/2021,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,3/11/2020,http://www.hatfield-saunders.net/

In [72]:
df.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000